### ISSUE TITLE
-translate-x-* and -translate-y-* are ignored

### ISSUE THREAD

**Issue by connecteev** [vesper8/vue-tailwind-prefix-applicator#3]
One minor bug on https://github.vue.tailwind-prefix.cbass.dev/

-translate-x-1/2 -translate-y-1/4
are ignored and should become:
tw--translate-x-1/2 tw--translate-y-1/4
Similarly for other negative values (of translate, etc)

**Comment by kiliman** [comment]
I still need to test this, but here's what I have:

Notice it supports both leading and non-leading hyphens. It also supports the responsive variant prefix. 

![image](https://user-images.githubusercontent.com/47168/79644166-1fa0a580-8175-11ea-892e-09d697b85c8b.png)

**Comment by kiliman** [comment]
It works, unfortunately, since the process loops through all the class names, it's ends up adding the prefixes multiple time... so need to improve the regular expression. Anyway, I'll make sure this is working before I push my transformer.

**Comment by connecteev** [comment]
Awesome...cant wait to use this. Did it involve pushing changes back to this (vesper8/vue-tailwind-prefix-applicator) codebase? Or did you clone the functionality into [your repo](https://github.com/kiliman/tailwindui-crawler)?

**Comment by kiliman** [comment]
Ok, I think I figured it out. Negative lookbehind doesn't seem to be working properly, so had to tweak the regex. It ensures that it doesn't reprocess the prefixed class on subsequent passes, especially when there are subsets... e.g., transform-x-1 vs transform-x-1/2

![image](https://user-images.githubusercontent.com/47168/79669072-102a5800-8187-11ea-9ddc-1f22a345ea97.png)

![image](https://user-images.githubusercontent.com/47168/79669171-b5ddc700-8187-11ea-999d-fe7bfe984b5d.png)

**Comment by kiliman** [comment]
@connecteev it was literally about 6 lines of code and a file with all the tailwind class names. I'll make a PR once we've confirmed that it's working properly in the transformer.

**Comment by kiliman** [comment]
@vesper8 I added you to all-contributors. Thanks for the asssist!

![image](https://user-images.githubusercontent.com/47168/79670171-13c1dd00-818f-11ea-96a2-c84a8e9f9b10.png)

**Comment by connecteev** [comment]
@kiliman @vesper8 that's great...thank you!

**Comment by vesper8** [comment]
> @vesper8 I added you to all-contributors. Thanks for the asssist!
> 
> ![image](https://user-images.githubusercontent.com/47168/79670171-13c1dd00-818f-11ea-96a2-c84a8e9f9b10.png)

thank you kind sir : ) much obliged


> @connecteev it was literally about 6 lines of code and a file with all the tailwind class names. I'll make a PR once we've confirmed that it's working properly in the transformer.

your approach seems very nice indeed, if you could indeed submit a PR that would be much appreciated

**Comment by vesper8** [comment]
@connecteev @kiliman I implemented the improvements you made so that `-translate-x-1/2` and other classes that begin with a hyphen are now supported

**Comment by connecteev** [comment]
@kiliman just a thought, since the same changes are going to go into your crawler repo (which is awesome) https://github.com/kiliman/tailwindui-crawler 
Does it make sense to have *one* source of truth? Perhaps this repo (assuming it continues to be as well-maintained as it is) be imported into your repo as a git submodule?
