### ISSUE TITLE
Support for tailwind 1.3.0

### ISSUE THREAD

**Issue by connecteev** [vesper8/vue-tailwind-prefix-applicator#4]
It would be nice to have tailwindcss integrate your library into the core.

That said, in the meantime 1.3.0 was just released: https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0

and adds space-*, divide-* and a few other styles

**Comment by vesper8** [comment]
Just commited https://github.com/vesper8/vue-tailwind-prefix-applicator/commit/b3513d4e0fb2982e690a8c8cb98b058d00323f38 which adds support for 1.3 : )

Also pushed the changes to https://github.vue.tailwind-prefix.cbass.dev

You might have to do a hard reload / cache clear before you get the changes

**Comment by connecteev** [comment]
That's awesome @vesper8 . I don't understand the code well enough, but it looks like you're creating the styles dynamically, which is great! Hopefully will make future integrations easier as tailwind evolves.

**Comment by vesper8** [comment]
Yea, the first one or two times I used multiple cursors and some find/replace magic to isolate all the tailwind class names manually but that was very tedious and time-consuming so I made a PHP script that loads up CSS files for tailwindcss and tailwind-ui and isolates all the class names and cleans up some suffixes and other unwanted artifacts. I still have to manually remove the normalize.css from those files first but afterward, it's just a matter of getting the latest versions and running the script which generates the tailwind-classes.js file
